
project_id = "lszauuplczqotjrogqgr"
[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]

[db]
seed_file = "supabase/seed.sql"

[functions.create-delete-user-function]
verify_jwt = true
[functions.delete-staff]
verify_jwt = true
[functions.delete-user-auth]
verify_jwt = true
[functions.reset-password-email]
verify_jwt = true
[functions.send-password-setup]
verify_jwt = true
[functions.setup-staff-deletion]
verify_jwt = true
[functions.clean-hotel-data]
verify_jwt = true

[realtime]
enabled = false

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
