// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lszauuplczqotjrogqgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzemF1dXBsY3pxb3Rqcm9ncWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDMxMDMsImV4cCI6MjA2MDgxOTEwM30.HHYjIWwbgwFutZJRJbgGYaOrdB6R8pUB_I8krpVbwek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);